# Generated by Django 6.0.1 on 2026-02-19 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0004_studentanswer'),
    ]

    operations = [
        migrations.AddField(
            model_name='examattempt',
            name='score',
            field=models.IntegerField(default=0),
        ),
    ]
